# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 01:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(choices=[('Insurance', 'Insurance'), ('Fitness', 'Fitness'), ('Pollution', 'Pollution')], max_length=20)),
                ('issue_date', models.DateField()),
                ('expire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice1', models.BooleanField(default=False)),
                ('notice2', models.BooleanField(default=False)),
                ('notice3', models.BooleanField(default=False)),
                ('read1', models.BooleanField(default=False)),
                ('read2', models.BooleanField(default=False)),
                ('read3', models.BooleanField(default=False)),
                ('certificate_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificationSystem.Certificate')),
            ],
        ),
        migrations.CreateModel(
            name='TruckDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=15, unique=True)),
                ('truck_number', models.CharField(max_length=12)),
                ('truck_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='truck_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificationSystem.TruckDetails'),
        ),
    ]
