# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notificationSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='time1',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notifications',
            name='time2',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notifications',
            name='time3',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
