# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationSystem', '0002_auto_20180316_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='issue_date',
        ),
    ]
